export {
  decodeMap,
  decodeTil,
  decodeBob,
  loadMap,
  loadTil,
  dac6to8,
  renderMapRgba,
  renderTilTileRgba,
  renderTilSheetRgba,
  renderMapComposedRgba,
  pickComposeTileSize,
  mapTileIndices,
  drawRgbaToCanvas,
  toImageData,
  heightmapToElevation,
  decodeAttr,
  attrMaterial,
  attrFlags,
  attrVariant,
  attrTileIndex,
  ATTR_FLAG,
  MapDecodeError,
  type TmMap,
  type TmTil,
  type TmBob,
  type TilTile,
  type BobObject,
  type MapViewMode,
  type AttrDecoded,
} from "./decode";

export {
  MAP_CATALOG,
  ORIGINAL_MAP_CATALOG,
  CREATIVE_MAP_CATALOG,
  MAP_CATALOG_COUNT,
  mapUrl,
  getMapEntry,
  type MapCatalogEntry,
} from "./catalog";

export {
  decodeLfx,
  decodeDfx,
  lfxRemap,
  dfxRemap,
  applyLfxToIndices,
  LfxDecodeError,
  type TmLfx,
  type TmDfx,
} from "./lfx";
